"""add AI fields to articles

Revision ID: 4d8c4f864c4f
Revises: 
Create Date: 2026-09-05 23:47:51.052491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8c4f864c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('key_points', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'key_points')
    op.drop_column('articles', 'ai_summary')
    # ### end Alembic commands ###
